# Mapping from Sports-Reference slug -> (display_name, torvik_name)
# Torvik name is as it appears on barttorvik.com
# Hand-maintained for the 68 teams in the 2026 NCAA Tournament

TEAM_MAP = {
    # East Region
    "duke": ("Duke", "Duke"),
    "alabama": ("Alabama", "Alabama"),
    "iowa-state": ("Iowa State", "Iowa St."),
    "maryland": ("Maryland", "Maryland"),
    "mississippi-state": ("Mississippi State", "Mississippi St."),
    "memphis": ("Memphis", "Memphis"),
    "uconn": ("UConn", "Connecticut"),
    "gonzaga": ("Gonzaga", "Gonzaga"),
    "byu": ("BYU", "BYU"),
    "new-mexico": ("New Mexico", "New Mexico"),
    "vcu": ("VCU", "VCU"),
    "liberty": ("Liberty", "Liberty"),
    "yale": ("Yale", "Yale"),
    "morehead-state": ("Morehead State", "Morehead St."),
    "siena": ("Siena", "Siena"),
    "mount-st-marys": ("Mount St. Mary's", "Mt. St. Mary's"),

    # West Region
    "arizona": ("Arizona", "Arizona"),
    "st-johns": ("St. John's", "St. John's"),
    "kentucky": ("Kentucky", "Kentucky"),
    "purdue": ("Purdue", "Purdue"),
    "wisconsin": ("Wisconsin", "Wisconsin"),
    "clemson": ("Clemson", "Clemson"),
    "ucla": ("UCLA", "UCLA"),
    "creighton": ("Creighton", "Creighton"),
    "vanderbilt": ("Vanderbilt", "Vanderbilt"),
    "utah-state": ("Utah State", "Utah St."),
    "texas": ("Texas", "Texas"),
    "nc-state": ("NC State", "NC State"),
    "akron": ("Akron", "Akron"),
    "high-point": ("High Point", "High Point"),
    "troy": ("Troy", "Troy"),
    "lipscomb": ("Lipscomb", "Lipscomb"),

    # Midwest Region
    "michigan": ("Michigan", "Michigan"),
    "tennessee": ("Tennessee", "Tennessee"),
    "texas-am": ("Texas A&M", "Texas A&M"),
    "baylor": ("Baylor", "Baylor"),
    "ohio-state": ("Ohio State", "Ohio St."),
    "illinois": ("Illinois", "Illinois"),
    "kansas": ("Kansas", "Kansas"),
    "mississippi": ("Ole Miss", "Mississippi"),
    "wake-forest": ("Wake Forest", "Wake Forest"),
    "drake": ("Drake", "Drake"),
    "umbc": ("UMBC", "UMBC"),
    "howard": ("Howard", "Howard"),
    "miami-oh": ("Miami (OH)", "Miami OH"),
    "smu": ("SMU", "SMU"),
    "central-arkansas": ("Central Arkansas", "Cent. Arkansas"),
    "siu-edwardsville": ("SIU Edwardsville", "SIU Edwardsville"),
    "stanford": ("Stanford", "Stanford"),

    # South Region
    "florida": ("Florida", "Florida"),
    "st-marys-ca": ("Saint Mary's", "Saint Mary's"),
    "lsu": ("LSU", "LSU"),
    "marquette": ("Marquette", "Marquette"),
    "michigan-state": ("Michigan State", "Michigan St."),
    "pittsburgh": ("Pittsburgh", "Pittsburgh"),
    "kansas-state": ("Kansas State", "Kansas St."),
    "notre-dame": ("Notre Dame", "Notre Dame"),
    "west-virginia": ("West Virginia", "West Virginia"),
    "villanova": ("Villanova", "Villanova"),
    "prairie-view": ("Prairie View A&M", "Prairie View"),
    "lehigh": ("Lehigh", "Lehigh"),
    "colgate": ("Colgate", "Colgate"),
    "charlotte": ("Charlotte", "Charlotte"),
    "southeastern-louisiana": ("SE Louisiana", "SE Louisiana"),
    "norfolk-state": ("Norfolk State", "Norfolk St."),
    "long-beach-state": ("Long Beach State", "Long Beach St."),
}
